# Generated by Django 6.0.6 on 2026-06-11 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('equipements', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_cours', "En cours d'opération"), ('nettoyage', 'En nettoyage'), ('hors_service', 'Hors service')], default='disponible', max_length=15)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('duree_estimee_minutes', models.IntegerField(default=60)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_prevue', models.DateTimeField()),
                ('duree_prevue_minutes', models.IntegerField(default=60)),
                ('niveau_urgence', models.CharField(choices=[('elective', 'Électif (programmé)'), ('urgent', 'Urgent'), ('urgence_vitale', 'Urgence vitale')], default='elective', max_length=15)),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='programme', max_length=15)),
                ('indication', models.TextField()),
                ('technique_prevue', models.TextField(blank=True)),
                ('materiel_special', models.TextField(blank=True)),
                ('risques_anesthesiques', models.TextField(blank=True)),
                ('consentement_signe', models.BooleanField(default=False)),
                ('bilan_preop_valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anesthesiste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_anesthesiste', to=settings.AUTH_USER_MODEL)),
                ('chirurgien_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_chirurgien', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes_crees', to=settings.AUTH_USER_MODEL)),
                ('equipe', models.ManyToManyField(blank=True, related_name='operations_equipe', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes_operatoires', to='patients.patient')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloc_operatoire.salleoperation')),
                ('type_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloc_operatoire.typeintervention')),
            ],
            options={
                'ordering': ['date_heure_prevue'],
            },
        ),
        migrations.CreateModel(
            name='CompteRenduOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('technique_utilisee', models.TextField()),
                ('incidents', models.TextField(blank=True)),
                ('pertes_sanguines_ml', models.IntegerField(blank=True, null=True)),
                ('transfusion', models.BooleanField(default=False)),
                ('produits_utilises', models.TextField(blank=True)),
                ('suites_operatoires', models.TextField(blank=True)),
                ('prescriptions_postop', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anesthesiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_rendus_anesthesiste', to=settings.AUTH_USER_MODEL)),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_rendus_chirurgien', to=settings.AUTH_USER_MODEL)),
                ('programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_rendu', to='bloc_operatoire.programmeoperatoire')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistPreoperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identite_verifiee', models.BooleanField(default=False)),
                ('site_marque', models.BooleanField(default=False)),
                ('consentement_present', models.BooleanField(default=False)),
                ('bilan_sanguin_ok', models.BooleanField(default=False)),
                ('ecg_ok', models.BooleanField(default=False)),
                ('radiologie_ok', models.BooleanField(default=False)),
                ('allergie_verifiee', models.BooleanField(default=False)),
                ('jeun_verifie', models.BooleanField(default=False)),
                ('voie_veineuse_posee', models.BooleanField(default=False)),
                ('antibioprophylaxie', models.BooleanField(default=False)),
                ('materiel_verifie', models.BooleanField(default=False)),
                ('equipe_complete', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('validee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='bloc_operatoire.programmeoperatoire')),
            ],
        ),
    ]
