# Generated by Django 6.0.6 on 2026-06-11 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('type_chambre', models.CharField(choices=[('standard', 'Standard'), ('semi_prive', 'Semi-privée'), ('prive', 'Privée'), ('soins_intensifs', 'Soins intensifs'), ('isolation', 'Isolement')], default='standard', max_length=20)),
                ('etage', models.IntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupe', 'Occupé'), ('nettoyage', 'En nettoyage'), ('hors_service', 'Hors service')], default='libre', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospitalisation.chambre')),
            ],
            options={
                'unique_together': {('chambre', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacite', models.IntegerField(default=10)),
                ('actif', models.BooleanField(default=True)),
                ('batiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitalisation.batiment')),
                ('chef_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_entree', models.CharField(choices=[('urgence', 'Urgences'), ('programmee', 'Programmée'), ('transfert', 'Transfert interne'), ('externe', 'Transfert externe')], default='programmee', max_length=15)),
                ('date_entree', models.DateTimeField()),
                ('date_sortie_prevue', models.DateField(blank=True, null=True)),
                ('date_sortie_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('sortie_prevue', 'Sortie prévue'), ('sorti', 'Sorti'), ('transfere', 'Transféré'), ('dcd', 'Décédé')], default='en_cours', max_length=15)),
                ('motif_hospitalisation', models.TextField()),
                ('diagnostic_entree', models.TextField(blank=True)),
                ('diagnostic_sortie', models.TextField(blank=True)),
                ('compte_rendu_sortie', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_creees', to=settings.AUTH_USER_MODEL)),
                ('medecin_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalisations_responsable', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='patients.patient')),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='hospitalisation.lit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalisation.service')),
            ],
            options={
                'ordering': ['-date_entree'],
            },
        ),
        migrations.AddField(
            model_name='chambre',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hospitalisation.service'),
        ),
        migrations.CreateModel(
            name='SuiviQuotidien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tension', models.CharField(blank=True, max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frequence_cardiaque', models.IntegerField(blank=True, null=True)),
                ('saturation_o2', models.IntegerField(blank=True, null=True)),
                ('evolution', models.TextField()),
                ('traitement_en_cours', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('prescriptions_nouvelles', models.TextField(blank=True)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='hospitalisation.hospitalisation')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransfertService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='hospitalisation.hospitalisation')),
                ('lit_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_arrivee', to='hospitalisation.lit')),
                ('lit_origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_depart', to='hospitalisation.lit')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_arrivee', to='hospitalisation.service')),
                ('service_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_depart', to='hospitalisation.service')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chambre',
            unique_together={('service', 'numero')},
        ),
    ]
