# Generated by Django 6.0.6 on 2026-06-10 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delai_heures', models.IntegerField(default=24)),
                ('valeurs_normales', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandée'), ('en_cours', 'En cours'), ('termine', 'Terminée'), ('annule', 'Annulée')], default='demande', max_length=15)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('urgente', 'Urgente'), ('tres_urgente', 'Très urgente')], default='normale', max_length=15)),
                ('notes_cliniques', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('laborantin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_traitees', to=settings.AUTH_USER_MODEL)),
                ('medecin_prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_prescrites', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.patient')),
                ('types_analyses', models.ManyToManyField(to='laboratoire.typeanalyse')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField()),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('interpretation', models.TextField(blank=True)),
                ('anormal', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='analyses/')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='laboratoire.demandeanalyse')),
                ('laborantin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.typeanalyse')),
            ],
        ),
    ]
