# Generated by Django 6.0.6 on 2026-06-11 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateTimeField(auto_now_add=True)),
                ('date_triage', models.DateTimeField(blank=True, null=True)),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_venue', models.TextField()),
                ('niveau_triage', models.IntegerField(blank=True, choices=[(1, 'P1 — Rouge / Immédiat'), (2, 'P2 — Orange / Très urgent'), (3, 'P3 — Jaune / Urgent'), (4, 'P4 — Vert / Peu urgent'), (5, 'P5 — Blanc / Non urgent')], null=True)),
                ('statut', models.CharField(choices=[('attente_triage', 'En attente triage'), ('triage_fait', 'Trié — attente prise en charge'), ('en_cours', 'Prise en charge en cours'), ('observation', 'En observation'), ('hospitalise', 'Hospitalisé'), ('sorti', 'Sorti'), ('dcd', 'Décédé'), ('parti_sans_soins', 'Parti sans soins')], default='attente_triage', max_length=25)),
                ('motif_sortie', models.CharField(blank=True, choices=[('domicile', 'Retour domicile'), ('hospitalisation', 'Hospitalisation'), ('transfert', 'Transfert établissement'), ('dcd', 'Décès'), ('pss', 'Parti sans soins')], max_length=20)),
                ('tension', models.CharField(blank=True, max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frequence_cardiaque', models.IntegerField(blank=True, null=True)),
                ('saturation_o2', models.IntegerField(blank=True, null=True)),
                ('frequence_respiratoire', models.IntegerField(blank=True, null=True)),
                ('glasgow', models.IntegerField(blank=True, help_text='Score de Glasgow 3-15', null=True)),
                ('symptomes', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('traitement_urgence', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages_crees', to=settings.AUTH_USER_MODEL)),
                ('infirmier_triage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_effectues', to=settings.AUTH_USER_MODEL)),
                ('medecin_prise_en_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgences_prises_en_charge', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_urgence', to='patients.patient')),
            ],
            options={
                'ordering': ['niveau_triage', 'date_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='ActeUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('heure', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('realise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='urgences.passageurgence')),
            ],
            options={
                'ordering': ['heure'],
            },
        ),
    ]
