# Generated by Django 6.0.6 on 2026-06-10 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DispensationMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='consultations.ordonnance')),
                ('pharmacien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nom_generique', models.CharField(blank=True, max_length=200)),
                ('forme', models.CharField(choices=[('comprime', 'Comprimé'), ('sirop', 'Sirop'), ('injection', 'Injection'), ('creme', 'Crème'), ('gouttes', 'Gouttes'), ('autre', 'Autre')], max_length=20)),
                ('dosage', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimum', models.IntegerField(default=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.categoriemedicament')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=15)),
                ('quantite', models.IntegerField()),
                ('motif', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stock_avant', models.IntegerField()),
                ('stock_apres', models.IntegerField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pharmacie.medicament')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
